### ISSUE TITLE
ERROR: Signature extraction failed, KeyError QV

### ISSUE THREAD

**Issue by HyperJAK** [HyperJAK/Youtube-Downloader#4]
Wait until youtube-dl library updates with a fix.

## Error:
---
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.py", line 1585, in _decrypt_signature
  File "youtube_dl\extractor\youtube.py", line 1510, in _extract_signature_function
  File "youtube_dl\extractor\youtube.py", line 1574, in <lambda>
  File "youtube_dl\jsinterp.py", line 37, in __call__
  File "youtube_dl\jsinterp.py", line 1039, in resf
  File "youtube_dl\jsinterp.py", line 443, in interpret_statement
  File "youtube_dl\jsinterp.py", line 917, in interpret_statement
  File "youtube_dl\jsinterp.py", line 909, in eval_method
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---

**Comment by PeekMe01** [comment]
you should do the fix instead of waiting foryoutube-dl library to fix it :)
